/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSuperadminDashboardRouteImport } from './routes/_authenticated/superadmin.dashboard'
import { Route as AuthenticatedMastersTariffRouteImport } from './routes/_authenticated/masters.tariff'
import { Route as AuthenticatedMastersStaffRouteImport } from './routes/_authenticated/masters.staff'
import { Route as AuthenticatedMastersRoomsRouteImport } from './routes/_authenticated/masters.rooms'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminDashboardRoute =
  AuthenticatedSuperadminDashboardRouteImport.update({
    id: '/superadmin/dashboard',
    path: '/superadmin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersTariffRoute =
  AuthenticatedMastersTariffRouteImport.update({
    id: '/masters/tariff',
    path: '/masters/tariff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersStaffRoute =
  AuthenticatedMastersStaffRouteImport.update({
    id: '/masters/staff',
    path: '/masters/staff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersRoomsRoute =
  AuthenticatedMastersRoomsRouteImport.update({
    id: '/masters/rooms',
    path: '/masters/rooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/_authenticated/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/_authenticated/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/_authenticated/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/properties'
    | '/masters/rooms'
    | '/masters/staff'
    | '/masters/tariff'
    | '/superadmin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/properties'
    | '/masters/rooms'
    | '/masters/staff'
    | '/masters/tariff'
    | '/superadmin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/properties'
    | '/_authenticated/masters/rooms'
    | '/_authenticated/masters/staff'
    | '/_authenticated/masters/tariff'
    | '/_authenticated/superadmin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/dashboard': {
      id: '/_authenticated/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperadminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/tariff': {
      id: '/_authenticated/masters/tariff'
      path: '/masters/tariff'
      fullPath: '/masters/tariff'
      preLoaderRoute: typeof AuthenticatedMastersTariffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/staff': {
      id: '/_authenticated/masters/staff'
      path: '/masters/staff'
      fullPath: '/masters/staff'
      preLoaderRoute: typeof AuthenticatedMastersStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/rooms': {
      id: '/_authenticated/masters/rooms'
      path: '/masters/rooms'
      fullPath: '/masters/rooms'
      preLoaderRoute: typeof AuthenticatedMastersRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedMastersRoomsRoute: typeof AuthenticatedMastersRoomsRoute
  AuthenticatedMastersStaffRoute: typeof AuthenticatedMastersStaffRoute
  AuthenticatedMastersTariffRoute: typeof AuthenticatedMastersTariffRoute
  AuthenticatedSuperadminDashboardRoute: typeof AuthenticatedSuperadminDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedMastersRoomsRoute: AuthenticatedMastersRoomsRoute,
  AuthenticatedMastersStaffRoute: AuthenticatedMastersStaffRoute,
  AuthenticatedMastersTariffRoute: AuthenticatedMastersTariffRoute,
  AuthenticatedSuperadminDashboardRoute: AuthenticatedSuperadminDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
