/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSuperadminDashboardRouteImport } from './routes/_authenticated/superadmin.dashboard'
import { Route as AuthenticatedReportsGstRouteImport } from './routes/_authenticated/reports.gst'
import { Route as AuthenticatedReportsDailyRouteImport } from './routes/_authenticated/reports.daily'
import { Route as AuthenticatedMastersTariffRouteImport } from './routes/_authenticated/masters.tariff'
import { Route as AuthenticatedMastersStaffRouteImport } from './routes/_authenticated/masters.staff'
import { Route as AuthenticatedMastersRoomsRouteImport } from './routes/_authenticated/masters.rooms'
import { Route as AuthenticatedMastersPrintersRouteImport } from './routes/_authenticated/masters.printers'
import { Route as AuthenticatedMastersMenuRouteImport } from './routes/_authenticated/masters.menu'
import { Route as AuthenticatedMastersHallsRouteImport } from './routes/_authenticated/masters.halls'
import { Route as AuthenticatedFrontDeskNewRouteImport } from './routes/_authenticated/front-desk.new'
import { Route as AuthenticatedFrontDeskInHouseRouteImport } from './routes/_authenticated/front-desk.in-house'
import { Route as AuthenticatedFrontDeskBookingsRouteImport } from './routes/_authenticated/front-desk.bookings'
import { Route as AuthenticatedFoodNewRouteImport } from './routes/_authenticated/food.new'
import { Route as AuthenticatedFoodKotsRouteImport } from './routes/_authenticated/food.kots'
import { Route as AuthenticatedFoodDashboardRouteImport } from './routes/_authenticated/food.dashboard'
import { Route as AuthenticatedBillingInvoicesRouteImport } from './routes/_authenticated/billing.invoices'
import { Route as AuthenticatedBanquetNewRouteImport } from './routes/_authenticated/banquet.new'
import { Route as AuthenticatedBanquetBookingsRouteImport } from './routes/_authenticated/banquet.bookings'
import { Route as AuthenticatedFrontDeskBookingIdRouteImport } from './routes/_authenticated/front-desk.booking.$id'
import { Route as AuthenticatedFoodKotIdRouteImport } from './routes/_authenticated/food.kot.$id'
import { Route as AuthenticatedBillingFolioBookingIdRouteImport } from './routes/_authenticated/billing.folio.$bookingId'
import { Route as AuthenticatedBanquetEventIdRouteImport } from './routes/_authenticated/banquet.event.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminDashboardRoute =
  AuthenticatedSuperadminDashboardRouteImport.update({
    id: '/superadmin/dashboard',
    path: '/superadmin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsGstRoute = AuthenticatedReportsGstRouteImport.update({
  id: '/reports/gst',
  path: '/reports/gst',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsDailyRoute =
  AuthenticatedReportsDailyRouteImport.update({
    id: '/reports/daily',
    path: '/reports/daily',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersTariffRoute =
  AuthenticatedMastersTariffRouteImport.update({
    id: '/masters/tariff',
    path: '/masters/tariff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersStaffRoute =
  AuthenticatedMastersStaffRouteImport.update({
    id: '/masters/staff',
    path: '/masters/staff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersRoomsRoute =
  AuthenticatedMastersRoomsRouteImport.update({
    id: '/masters/rooms',
    path: '/masters/rooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersPrintersRoute =
  AuthenticatedMastersPrintersRouteImport.update({
    id: '/masters/printers',
    path: '/masters/printers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMenuRoute =
  AuthenticatedMastersMenuRouteImport.update({
    id: '/masters/menu',
    path: '/masters/menu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersHallsRoute =
  AuthenticatedMastersHallsRouteImport.update({
    id: '/masters/halls',
    path: '/masters/halls',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskNewRoute =
  AuthenticatedFrontDeskNewRouteImport.update({
    id: '/front-desk/new',
    path: '/front-desk/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskInHouseRoute =
  AuthenticatedFrontDeskInHouseRouteImport.update({
    id: '/front-desk/in-house',
    path: '/front-desk/in-house',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskBookingsRoute =
  AuthenticatedFrontDeskBookingsRouteImport.update({
    id: '/front-desk/bookings',
    path: '/front-desk/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoodNewRoute = AuthenticatedFoodNewRouteImport.update({
  id: '/food/new',
  path: '/food/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodKotsRoute = AuthenticatedFoodKotsRouteImport.update({
  id: '/food/kots',
  path: '/food/kots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodDashboardRoute =
  AuthenticatedFoodDashboardRouteImport.update({
    id: '/food/dashboard',
    path: '/food/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingInvoicesRoute =
  AuthenticatedBillingInvoicesRouteImport.update({
    id: '/billing/invoices',
    path: '/billing/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBanquetNewRoute = AuthenticatedBanquetNewRouteImport.update({
  id: '/banquet/new',
  path: '/banquet/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBanquetBookingsRoute =
  AuthenticatedBanquetBookingsRouteImport.update({
    id: '/banquet/bookings',
    path: '/banquet/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskBookingIdRoute =
  AuthenticatedFrontDeskBookingIdRouteImport.update({
    id: '/front-desk/booking/$id',
    path: '/front-desk/booking/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoodKotIdRoute = AuthenticatedFoodKotIdRouteImport.update({
  id: '/food/kot/$id',
  path: '/food/kot/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingFolioBookingIdRoute =
  AuthenticatedBillingFolioBookingIdRouteImport.update({
    id: '/billing/folio/$bookingId',
    path: '/billing/folio/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBanquetEventIdRoute =
  AuthenticatedBanquetEventIdRouteImport.update({
    id: '/banquet/event/$id',
    path: '/banquet/event/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/banquet/bookings': typeof AuthenticatedBanquetBookingsRoute
  '/banquet/new': typeof AuthenticatedBanquetNewRoute
  '/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/food/dashboard': typeof AuthenticatedFoodDashboardRoute
  '/food/kots': typeof AuthenticatedFoodKotsRoute
  '/food/new': typeof AuthenticatedFoodNewRoute
  '/front-desk/bookings': typeof AuthenticatedFrontDeskBookingsRoute
  '/front-desk/in-house': typeof AuthenticatedFrontDeskInHouseRoute
  '/front-desk/new': typeof AuthenticatedFrontDeskNewRoute
  '/masters/halls': typeof AuthenticatedMastersHallsRoute
  '/masters/menu': typeof AuthenticatedMastersMenuRoute
  '/masters/printers': typeof AuthenticatedMastersPrintersRoute
  '/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/gst': typeof AuthenticatedReportsGstRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/banquet/event/$id': typeof AuthenticatedBanquetEventIdRoute
  '/billing/folio/$bookingId': typeof AuthenticatedBillingFolioBookingIdRoute
  '/food/kot/$id': typeof AuthenticatedFoodKotIdRoute
  '/front-desk/booking/$id': typeof AuthenticatedFrontDeskBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/banquet/bookings': typeof AuthenticatedBanquetBookingsRoute
  '/banquet/new': typeof AuthenticatedBanquetNewRoute
  '/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/food/dashboard': typeof AuthenticatedFoodDashboardRoute
  '/food/kots': typeof AuthenticatedFoodKotsRoute
  '/food/new': typeof AuthenticatedFoodNewRoute
  '/front-desk/bookings': typeof AuthenticatedFrontDeskBookingsRoute
  '/front-desk/in-house': typeof AuthenticatedFrontDeskInHouseRoute
  '/front-desk/new': typeof AuthenticatedFrontDeskNewRoute
  '/masters/halls': typeof AuthenticatedMastersHallsRoute
  '/masters/menu': typeof AuthenticatedMastersMenuRoute
  '/masters/printers': typeof AuthenticatedMastersPrintersRoute
  '/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/gst': typeof AuthenticatedReportsGstRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/banquet/event/$id': typeof AuthenticatedBanquetEventIdRoute
  '/billing/folio/$bookingId': typeof AuthenticatedBillingFolioBookingIdRoute
  '/food/kot/$id': typeof AuthenticatedFoodKotIdRoute
  '/front-desk/booking/$id': typeof AuthenticatedFrontDeskBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/banquet/bookings': typeof AuthenticatedBanquetBookingsRoute
  '/_authenticated/banquet/new': typeof AuthenticatedBanquetNewRoute
  '/_authenticated/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/_authenticated/food/dashboard': typeof AuthenticatedFoodDashboardRoute
  '/_authenticated/food/kots': typeof AuthenticatedFoodKotsRoute
  '/_authenticated/food/new': typeof AuthenticatedFoodNewRoute
  '/_authenticated/front-desk/bookings': typeof AuthenticatedFrontDeskBookingsRoute
  '/_authenticated/front-desk/in-house': typeof AuthenticatedFrontDeskInHouseRoute
  '/_authenticated/front-desk/new': typeof AuthenticatedFrontDeskNewRoute
  '/_authenticated/masters/halls': typeof AuthenticatedMastersHallsRoute
  '/_authenticated/masters/menu': typeof AuthenticatedMastersMenuRoute
  '/_authenticated/masters/printers': typeof AuthenticatedMastersPrintersRoute
  '/_authenticated/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/_authenticated/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/_authenticated/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/_authenticated/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/_authenticated/reports/gst': typeof AuthenticatedReportsGstRoute
  '/_authenticated/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/_authenticated/banquet/event/$id': typeof AuthenticatedBanquetEventIdRoute
  '/_authenticated/billing/folio/$bookingId': typeof AuthenticatedBillingFolioBookingIdRoute
  '/_authenticated/food/kot/$id': typeof AuthenticatedFoodKotIdRoute
  '/_authenticated/front-desk/booking/$id': typeof AuthenticatedFrontDeskBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/properties'
    | '/banquet/bookings'
    | '/banquet/new'
    | '/billing/invoices'
    | '/food/dashboard'
    | '/food/kots'
    | '/food/new'
    | '/front-desk/bookings'
    | '/front-desk/in-house'
    | '/front-desk/new'
    | '/masters/halls'
    | '/masters/menu'
    | '/masters/printers'
    | '/masters/rooms'
    | '/masters/staff'
    | '/masters/tariff'
    | '/reports/daily'
    | '/reports/gst'
    | '/superadmin/dashboard'
    | '/banquet/event/$id'
    | '/billing/folio/$bookingId'
    | '/food/kot/$id'
    | '/front-desk/booking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/properties'
    | '/banquet/bookings'
    | '/banquet/new'
    | '/billing/invoices'
    | '/food/dashboard'
    | '/food/kots'
    | '/food/new'
    | '/front-desk/bookings'
    | '/front-desk/in-house'
    | '/front-desk/new'
    | '/masters/halls'
    | '/masters/menu'
    | '/masters/printers'
    | '/masters/rooms'
    | '/masters/staff'
    | '/masters/tariff'
    | '/reports/daily'
    | '/reports/gst'
    | '/superadmin/dashboard'
    | '/banquet/event/$id'
    | '/billing/folio/$bookingId'
    | '/food/kot/$id'
    | '/front-desk/booking/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/properties'
    | '/_authenticated/banquet/bookings'
    | '/_authenticated/banquet/new'
    | '/_authenticated/billing/invoices'
    | '/_authenticated/food/dashboard'
    | '/_authenticated/food/kots'
    | '/_authenticated/food/new'
    | '/_authenticated/front-desk/bookings'
    | '/_authenticated/front-desk/in-house'
    | '/_authenticated/front-desk/new'
    | '/_authenticated/masters/halls'
    | '/_authenticated/masters/menu'
    | '/_authenticated/masters/printers'
    | '/_authenticated/masters/rooms'
    | '/_authenticated/masters/staff'
    | '/_authenticated/masters/tariff'
    | '/_authenticated/reports/daily'
    | '/_authenticated/reports/gst'
    | '/_authenticated/superadmin/dashboard'
    | '/_authenticated/banquet/event/$id'
    | '/_authenticated/billing/folio/$bookingId'
    | '/_authenticated/food/kot/$id'
    | '/_authenticated/front-desk/booking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/dashboard': {
      id: '/_authenticated/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperadminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/gst': {
      id: '/_authenticated/reports/gst'
      path: '/reports/gst'
      fullPath: '/reports/gst'
      preLoaderRoute: typeof AuthenticatedReportsGstRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/daily': {
      id: '/_authenticated/reports/daily'
      path: '/reports/daily'
      fullPath: '/reports/daily'
      preLoaderRoute: typeof AuthenticatedReportsDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/tariff': {
      id: '/_authenticated/masters/tariff'
      path: '/masters/tariff'
      fullPath: '/masters/tariff'
      preLoaderRoute: typeof AuthenticatedMastersTariffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/staff': {
      id: '/_authenticated/masters/staff'
      path: '/masters/staff'
      fullPath: '/masters/staff'
      preLoaderRoute: typeof AuthenticatedMastersStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/rooms': {
      id: '/_authenticated/masters/rooms'
      path: '/masters/rooms'
      fullPath: '/masters/rooms'
      preLoaderRoute: typeof AuthenticatedMastersRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/printers': {
      id: '/_authenticated/masters/printers'
      path: '/masters/printers'
      fullPath: '/masters/printers'
      preLoaderRoute: typeof AuthenticatedMastersPrintersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/menu': {
      id: '/_authenticated/masters/menu'
      path: '/masters/menu'
      fullPath: '/masters/menu'
      preLoaderRoute: typeof AuthenticatedMastersMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/halls': {
      id: '/_authenticated/masters/halls'
      path: '/masters/halls'
      fullPath: '/masters/halls'
      preLoaderRoute: typeof AuthenticatedMastersHallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/new': {
      id: '/_authenticated/front-desk/new'
      path: '/front-desk/new'
      fullPath: '/front-desk/new'
      preLoaderRoute: typeof AuthenticatedFrontDeskNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/in-house': {
      id: '/_authenticated/front-desk/in-house'
      path: '/front-desk/in-house'
      fullPath: '/front-desk/in-house'
      preLoaderRoute: typeof AuthenticatedFrontDeskInHouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/bookings': {
      id: '/_authenticated/front-desk/bookings'
      path: '/front-desk/bookings'
      fullPath: '/front-desk/bookings'
      preLoaderRoute: typeof AuthenticatedFrontDeskBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/new': {
      id: '/_authenticated/food/new'
      path: '/food/new'
      fullPath: '/food/new'
      preLoaderRoute: typeof AuthenticatedFoodNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/kots': {
      id: '/_authenticated/food/kots'
      path: '/food/kots'
      fullPath: '/food/kots'
      preLoaderRoute: typeof AuthenticatedFoodKotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/dashboard': {
      id: '/_authenticated/food/dashboard'
      path: '/food/dashboard'
      fullPath: '/food/dashboard'
      preLoaderRoute: typeof AuthenticatedFoodDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/invoices': {
      id: '/_authenticated/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/billing/invoices'
      preLoaderRoute: typeof AuthenticatedBillingInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/new': {
      id: '/_authenticated/banquet/new'
      path: '/banquet/new'
      fullPath: '/banquet/new'
      preLoaderRoute: typeof AuthenticatedBanquetNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/bookings': {
      id: '/_authenticated/banquet/bookings'
      path: '/banquet/bookings'
      fullPath: '/banquet/bookings'
      preLoaderRoute: typeof AuthenticatedBanquetBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/booking/$id': {
      id: '/_authenticated/front-desk/booking/$id'
      path: '/front-desk/booking/$id'
      fullPath: '/front-desk/booking/$id'
      preLoaderRoute: typeof AuthenticatedFrontDeskBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/kot/$id': {
      id: '/_authenticated/food/kot/$id'
      path: '/food/kot/$id'
      fullPath: '/food/kot/$id'
      preLoaderRoute: typeof AuthenticatedFoodKotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/folio/$bookingId': {
      id: '/_authenticated/billing/folio/$bookingId'
      path: '/billing/folio/$bookingId'
      fullPath: '/billing/folio/$bookingId'
      preLoaderRoute: typeof AuthenticatedBillingFolioBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/event/$id': {
      id: '/_authenticated/banquet/event/$id'
      path: '/banquet/event/$id'
      fullPath: '/banquet/event/$id'
      preLoaderRoute: typeof AuthenticatedBanquetEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedBanquetBookingsRoute: typeof AuthenticatedBanquetBookingsRoute
  AuthenticatedBanquetNewRoute: typeof AuthenticatedBanquetNewRoute
  AuthenticatedBillingInvoicesRoute: typeof AuthenticatedBillingInvoicesRoute
  AuthenticatedFoodDashboardRoute: typeof AuthenticatedFoodDashboardRoute
  AuthenticatedFoodKotsRoute: typeof AuthenticatedFoodKotsRoute
  AuthenticatedFoodNewRoute: typeof AuthenticatedFoodNewRoute
  AuthenticatedFrontDeskBookingsRoute: typeof AuthenticatedFrontDeskBookingsRoute
  AuthenticatedFrontDeskInHouseRoute: typeof AuthenticatedFrontDeskInHouseRoute
  AuthenticatedFrontDeskNewRoute: typeof AuthenticatedFrontDeskNewRoute
  AuthenticatedMastersHallsRoute: typeof AuthenticatedMastersHallsRoute
  AuthenticatedMastersMenuRoute: typeof AuthenticatedMastersMenuRoute
  AuthenticatedMastersPrintersRoute: typeof AuthenticatedMastersPrintersRoute
  AuthenticatedMastersRoomsRoute: typeof AuthenticatedMastersRoomsRoute
  AuthenticatedMastersStaffRoute: typeof AuthenticatedMastersStaffRoute
  AuthenticatedMastersTariffRoute: typeof AuthenticatedMastersTariffRoute
  AuthenticatedReportsDailyRoute: typeof AuthenticatedReportsDailyRoute
  AuthenticatedReportsGstRoute: typeof AuthenticatedReportsGstRoute
  AuthenticatedSuperadminDashboardRoute: typeof AuthenticatedSuperadminDashboardRoute
  AuthenticatedBanquetEventIdRoute: typeof AuthenticatedBanquetEventIdRoute
  AuthenticatedBillingFolioBookingIdRoute: typeof AuthenticatedBillingFolioBookingIdRoute
  AuthenticatedFoodKotIdRoute: typeof AuthenticatedFoodKotIdRoute
  AuthenticatedFrontDeskBookingIdRoute: typeof AuthenticatedFrontDeskBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedBanquetBookingsRoute: AuthenticatedBanquetBookingsRoute,
  AuthenticatedBanquetNewRoute: AuthenticatedBanquetNewRoute,
  AuthenticatedBillingInvoicesRoute: AuthenticatedBillingInvoicesRoute,
  AuthenticatedFoodDashboardRoute: AuthenticatedFoodDashboardRoute,
  AuthenticatedFoodKotsRoute: AuthenticatedFoodKotsRoute,
  AuthenticatedFoodNewRoute: AuthenticatedFoodNewRoute,
  AuthenticatedFrontDeskBookingsRoute: AuthenticatedFrontDeskBookingsRoute,
  AuthenticatedFrontDeskInHouseRoute: AuthenticatedFrontDeskInHouseRoute,
  AuthenticatedFrontDeskNewRoute: AuthenticatedFrontDeskNewRoute,
  AuthenticatedMastersHallsRoute: AuthenticatedMastersHallsRoute,
  AuthenticatedMastersMenuRoute: AuthenticatedMastersMenuRoute,
  AuthenticatedMastersPrintersRoute: AuthenticatedMastersPrintersRoute,
  AuthenticatedMastersRoomsRoute: AuthenticatedMastersRoomsRoute,
  AuthenticatedMastersStaffRoute: AuthenticatedMastersStaffRoute,
  AuthenticatedMastersTariffRoute: AuthenticatedMastersTariffRoute,
  AuthenticatedReportsDailyRoute: AuthenticatedReportsDailyRoute,
  AuthenticatedReportsGstRoute: AuthenticatedReportsGstRoute,
  AuthenticatedSuperadminDashboardRoute: AuthenticatedSuperadminDashboardRoute,
  AuthenticatedBanquetEventIdRoute: AuthenticatedBanquetEventIdRoute,
  AuthenticatedBillingFolioBookingIdRoute:
    AuthenticatedBillingFolioBookingIdRoute,
  AuthenticatedFoodKotIdRoute: AuthenticatedFoodKotIdRoute,
  AuthenticatedFrontDeskBookingIdRoute: AuthenticatedFrontDeskBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
