/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWhatsappIndexRouteImport } from './routes/_authenticated/whatsapp.index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security.index'
import { Route as AuthenticatedRestaurantIndexRouteImport } from './routes/_authenticated/restaurant.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedPosIndexRouteImport } from './routes/_authenticated/pos.index'
import { Route as AuthenticatedMastersIndexRouteImport } from './routes/_authenticated/masters.index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedGuestsIndexRouteImport } from './routes/_authenticated/guests.index'
import { Route as AuthenticatedFeedbackIndexRouteImport } from './routes/_authenticated/feedback.index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses.index'
import { Route as AuthenticatedCommsIndexRouteImport } from './routes/_authenticated/comms.index'
import { Route as AuthenticatedChannelsIndexRouteImport } from './routes/_authenticated/channels.index'
import { Route as AuthenticatedSuperadminUsersRouteImport } from './routes/_authenticated/superadmin.users'
import { Route as AuthenticatedSuperadminDashboardRouteImport } from './routes/_authenticated/superadmin.dashboard'
import { Route as AuthenticatedStaffPayrollRouteImport } from './routes/_authenticated/staff.payroll'
import { Route as AuthenticatedStaffAttendanceHistoryRouteImport } from './routes/_authenticated/staff.attendance-history'
import { Route as AuthenticatedStaffAttendanceRouteImport } from './routes/_authenticated/staff.attendance'
import { Route as AuthenticatedSettingsWhatsappRouteImport } from './routes/_authenticated/settings.whatsapp'
import { Route as AuthenticatedSettingsHotelRouteImport } from './routes/_authenticated/settings.hotel'
import { Route as AuthenticatedRoomsRoomNumberRouteImport } from './routes/_authenticated/rooms.$roomNumber'
import { Route as AuthenticatedReportsSalesRouteImport } from './routes/_authenticated/reports.sales'
import { Route as AuthenticatedReportsRoomWiseRouteImport } from './routes/_authenticated/reports.room-wise'
import { Route as AuthenticatedReportsNightAuditRouteImport } from './routes/_authenticated/reports.night-audit'
import { Route as AuthenticatedReportsMisRouteImport } from './routes/_authenticated/reports.mis'
import { Route as AuthenticatedReportsGuestWiseRouteImport } from './routes/_authenticated/reports.guest-wise'
import { Route as AuthenticatedReportsGstRouteImport } from './routes/_authenticated/reports.gst'
import { Route as AuthenticatedReportsFoodKotRouteImport } from './routes/_authenticated/reports.food-kot'
import { Route as AuthenticatedReportsExpensesRouteImport } from './routes/_authenticated/reports.expenses'
import { Route as AuthenticatedReportsDateWiseRevenueRouteImport } from './routes/_authenticated/reports.date-wise-revenue'
import { Route as AuthenticatedReportsDailyRouteImport } from './routes/_authenticated/reports.daily'
import { Route as AuthenticatedReportsCashCollectionRouteImport } from './routes/_authenticated/reports.cash-collection'
import { Route as AuthenticatedReportsBillWiseRouteImport } from './routes/_authenticated/reports.bill-wise'
import { Route as AuthenticatedReportsBanquetRouteImport } from './routes/_authenticated/reports.banquet'
import { Route as AuthenticatedReportsAnalyticsRouteImport } from './routes/_authenticated/reports.analytics'
import { Route as AuthenticatedReportsActivityRouteImport } from './routes/_authenticated/reports.activity'
import { Route as AuthenticatedMastersTariffRouteImport } from './routes/_authenticated/masters.tariff'
import { Route as AuthenticatedMastersSundryItemsRouteImport } from './routes/_authenticated/masters.sundry-items'
import { Route as AuthenticatedMastersStaffRouteImport } from './routes/_authenticated/masters.staff'
import { Route as AuthenticatedMastersRoomsRouteImport } from './routes/_authenticated/masters.rooms'
import { Route as AuthenticatedMastersRateSeasonsRouteImport } from './routes/_authenticated/masters.rate-seasons'
import { Route as AuthenticatedMastersPrintersRouteImport } from './routes/_authenticated/masters.printers'
import { Route as AuthenticatedMastersMessageTemplatesRouteImport } from './routes/_authenticated/masters.message-templates'
import { Route as AuthenticatedMastersMenuRouteImport } from './routes/_authenticated/masters.menu'
import { Route as AuthenticatedMastersHallsRouteImport } from './routes/_authenticated/masters.halls'
import { Route as AuthenticatedMastersExpenseCategoriesRouteImport } from './routes/_authenticated/masters.expense-categories'
import { Route as AuthenticatedMastersChannelsRouteImport } from './routes/_authenticated/masters.channels'
import { Route as AuthenticatedInventoryVendorsRouteImport } from './routes/_authenticated/inventory.vendors'
import { Route as AuthenticatedInventoryStockRouteImport } from './routes/_authenticated/inventory.stock'
import { Route as AuthenticatedInventoryMovementsRouteImport } from './routes/_authenticated/inventory.movements'
import { Route as AuthenticatedInventoryItemsRouteImport } from './routes/_authenticated/inventory.items'
import { Route as AuthenticatedHousekeepingTasksRouteImport } from './routes/_authenticated/housekeeping.tasks'
import { Route as AuthenticatedHousekeepingNewRouteImport } from './routes/_authenticated/housekeeping.new'
import { Route as AuthenticatedHousekeepingBoardRouteImport } from './routes/_authenticated/housekeeping.board'
import { Route as AuthenticatedGuestsNewRouteImport } from './routes/_authenticated/guests.new'
import { Route as AuthenticatedGuestsIdRouteImport } from './routes/_authenticated/guests.$id'
import { Route as AuthenticatedFrontDeskRateCalendarRouteImport } from './routes/_authenticated/front-desk.rate-calendar'
import { Route as AuthenticatedFrontDeskNewRouteImport } from './routes/_authenticated/front-desk.new'
import { Route as AuthenticatedFrontDeskInHouseRouteImport } from './routes/_authenticated/front-desk.in-house'
import { Route as AuthenticatedFrontDeskCalendarRouteImport } from './routes/_authenticated/front-desk.calendar'
import { Route as AuthenticatedFrontDeskBookingsRouteImport } from './routes/_authenticated/front-desk.bookings'
import { Route as AuthenticatedFoodPendingBillsRouteImport } from './routes/_authenticated/food.pending-bills'
import { Route as AuthenticatedFoodNewRouteImport } from './routes/_authenticated/food.new'
import { Route as AuthenticatedFoodKotsRouteImport } from './routes/_authenticated/food.kots'
import { Route as AuthenticatedFoodDashboardRouteImport } from './routes/_authenticated/food.dashboard'
import { Route as AuthenticatedFeedbackNewRouteImport } from './routes/_authenticated/feedback.new'
import { Route as AuthenticatedExpensesNewRouteImport } from './routes/_authenticated/expenses.new'
import { Route as AuthenticatedCommsNewRouteImport } from './routes/_authenticated/comms.new'
import { Route as AuthenticatedBillingMisRouteImport } from './routes/_authenticated/billing.mis'
import { Route as AuthenticatedBillingInvoicesRouteImport } from './routes/_authenticated/billing.invoices'
import { Route as AuthenticatedBanquetNewRouteImport } from './routes/_authenticated/banquet.new'
import { Route as AuthenticatedBanquetBookingsRouteImport } from './routes/_authenticated/banquet.bookings'
import { Route as AuthenticatedFrontDeskBookingIdRouteImport } from './routes/_authenticated/front-desk.booking.$id'
import { Route as AuthenticatedFoodKotIdRouteImport } from './routes/_authenticated/food.kot.$id'
import { Route as AuthenticatedBillingFolioBookingIdRouteImport } from './routes/_authenticated/billing.folio.$bookingId'
import { Route as AuthenticatedBanquetEventIdRouteImport } from './routes/_authenticated/banquet.event.$id'
import { Route as AuthenticatedBanquetBillIdRouteImport } from './routes/_authenticated/banquet.bill.$id'
import { Route as AuthenticatedBanquetEventRouteImport } from './routes/_authenticated/banquet.event.'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappIndexRoute =
  AuthenticatedWhatsappIndexRouteImport.update({
    id: '/whatsapp/',
    path: '/whatsapp/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRestaurantIndexRoute =
  AuthenticatedRestaurantIndexRouteImport.update({
    id: '/restaurant/',
    path: '/restaurant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosIndexRoute = AuthenticatedPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMastersIndexRoute =
  AuthenticatedMastersIndexRouteImport.update({
    id: '/masters/',
    path: '/masters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestsIndexRoute =
  AuthenticatedGuestsIndexRouteImport.update({
    id: '/guests/',
    path: '/guests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackIndexRoute =
  AuthenticatedFeedbackIndexRouteImport.update({
    id: '/feedback/',
    path: '/feedback/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommsIndexRoute = AuthenticatedCommsIndexRouteImport.update({
  id: '/comms/',
  path: '/comms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminUsersRoute =
  AuthenticatedSuperadminUsersRouteImport.update({
    id: '/superadmin/users',
    path: '/superadmin/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSuperadminDashboardRoute =
  AuthenticatedSuperadminDashboardRouteImport.update({
    id: '/superadmin/dashboard',
    path: '/superadmin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffPayrollRoute =
  AuthenticatedStaffPayrollRouteImport.update({
    id: '/staff/payroll',
    path: '/staff/payroll',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffAttendanceHistoryRoute =
  AuthenticatedStaffAttendanceHistoryRouteImport.update({
    id: '/staff/attendance-history',
    path: '/staff/attendance-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffAttendanceRoute =
  AuthenticatedStaffAttendanceRouteImport.update({
    id: '/staff/attendance',
    path: '/staff/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsWhatsappRoute =
  AuthenticatedSettingsWhatsappRouteImport.update({
    id: '/settings/whatsapp',
    path: '/settings/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsHotelRoute =
  AuthenticatedSettingsHotelRouteImport.update({
    id: '/settings/hotel',
    path: '/settings/hotel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRoomsRoomNumberRoute =
  AuthenticatedRoomsRoomNumberRouteImport.update({
    id: '/rooms/$roomNumber',
    path: '/rooms/$roomNumber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsSalesRoute =
  AuthenticatedReportsSalesRouteImport.update({
    id: '/reports/sales',
    path: '/reports/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoomWiseRoute =
  AuthenticatedReportsRoomWiseRouteImport.update({
    id: '/reports/room-wise',
    path: '/reports/room-wise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsNightAuditRoute =
  AuthenticatedReportsNightAuditRouteImport.update({
    id: '/reports/night-audit',
    path: '/reports/night-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsMisRoute = AuthenticatedReportsMisRouteImport.update({
  id: '/reports/mis',
  path: '/reports/mis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsGuestWiseRoute =
  AuthenticatedReportsGuestWiseRouteImport.update({
    id: '/reports/guest-wise',
    path: '/reports/guest-wise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsGstRoute = AuthenticatedReportsGstRouteImport.update({
  id: '/reports/gst',
  path: '/reports/gst',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsFoodKotRoute =
  AuthenticatedReportsFoodKotRouteImport.update({
    id: '/reports/food-kot',
    path: '/reports/food-kot',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsExpensesRoute =
  AuthenticatedReportsExpensesRouteImport.update({
    id: '/reports/expenses',
    path: '/reports/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDateWiseRevenueRoute =
  AuthenticatedReportsDateWiseRevenueRouteImport.update({
    id: '/reports/date-wise-revenue',
    path: '/reports/date-wise-revenue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsDailyRoute =
  AuthenticatedReportsDailyRouteImport.update({
    id: '/reports/daily',
    path: '/reports/daily',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsCashCollectionRoute =
  AuthenticatedReportsCashCollectionRouteImport.update({
    id: '/reports/cash-collection',
    path: '/reports/cash-collection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsBillWiseRoute =
  AuthenticatedReportsBillWiseRouteImport.update({
    id: '/reports/bill-wise',
    path: '/reports/bill-wise',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsBanquetRoute =
  AuthenticatedReportsBanquetRouteImport.update({
    id: '/reports/banquet',
    path: '/reports/banquet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAnalyticsRoute =
  AuthenticatedReportsAnalyticsRouteImport.update({
    id: '/reports/analytics',
    path: '/reports/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsActivityRoute =
  AuthenticatedReportsActivityRouteImport.update({
    id: '/reports/activity',
    path: '/reports/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersTariffRoute =
  AuthenticatedMastersTariffRouteImport.update({
    id: '/masters/tariff',
    path: '/masters/tariff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersSundryItemsRoute =
  AuthenticatedMastersSundryItemsRouteImport.update({
    id: '/masters/sundry-items',
    path: '/masters/sundry-items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersStaffRoute =
  AuthenticatedMastersStaffRouteImport.update({
    id: '/masters/staff',
    path: '/masters/staff',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersRoomsRoute =
  AuthenticatedMastersRoomsRouteImport.update({
    id: '/masters/rooms',
    path: '/masters/rooms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersRateSeasonsRoute =
  AuthenticatedMastersRateSeasonsRouteImport.update({
    id: '/masters/rate-seasons',
    path: '/masters/rate-seasons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersPrintersRoute =
  AuthenticatedMastersPrintersRouteImport.update({
    id: '/masters/printers',
    path: '/masters/printers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMessageTemplatesRoute =
  AuthenticatedMastersMessageTemplatesRouteImport.update({
    id: '/masters/message-templates',
    path: '/masters/message-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersMenuRoute =
  AuthenticatedMastersMenuRouteImport.update({
    id: '/masters/menu',
    path: '/masters/menu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersHallsRoute =
  AuthenticatedMastersHallsRouteImport.update({
    id: '/masters/halls',
    path: '/masters/halls',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersExpenseCategoriesRoute =
  AuthenticatedMastersExpenseCategoriesRouteImport.update({
    id: '/masters/expense-categories',
    path: '/masters/expense-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMastersChannelsRoute =
  AuthenticatedMastersChannelsRouteImport.update({
    id: '/masters/channels',
    path: '/masters/channels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryVendorsRoute =
  AuthenticatedInventoryVendorsRouteImport.update({
    id: '/inventory/vendors',
    path: '/inventory/vendors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryStockRoute =
  AuthenticatedInventoryStockRouteImport.update({
    id: '/inventory/stock',
    path: '/inventory/stock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryMovementsRoute =
  AuthenticatedInventoryMovementsRouteImport.update({
    id: '/inventory/movements',
    path: '/inventory/movements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryItemsRoute =
  AuthenticatedInventoryItemsRouteImport.update({
    id: '/inventory/items',
    path: '/inventory/items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousekeepingTasksRoute =
  AuthenticatedHousekeepingTasksRouteImport.update({
    id: '/housekeeping/tasks',
    path: '/housekeeping/tasks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousekeepingNewRoute =
  AuthenticatedHousekeepingNewRouteImport.update({
    id: '/housekeeping/new',
    path: '/housekeeping/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousekeepingBoardRoute =
  AuthenticatedHousekeepingBoardRouteImport.update({
    id: '/housekeeping/board',
    path: '/housekeeping/board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuestsNewRoute = AuthenticatedGuestsNewRouteImport.update({
  id: '/guests/new',
  path: '/guests/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuestsIdRoute = AuthenticatedGuestsIdRouteImport.update({
  id: '/guests/$id',
  path: '/guests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrontDeskRateCalendarRoute =
  AuthenticatedFrontDeskRateCalendarRouteImport.update({
    id: '/front-desk/rate-calendar',
    path: '/front-desk/rate-calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskNewRoute =
  AuthenticatedFrontDeskNewRouteImport.update({
    id: '/front-desk/new',
    path: '/front-desk/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskInHouseRoute =
  AuthenticatedFrontDeskInHouseRouteImport.update({
    id: '/front-desk/in-house',
    path: '/front-desk/in-house',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskCalendarRoute =
  AuthenticatedFrontDeskCalendarRouteImport.update({
    id: '/front-desk/calendar',
    path: '/front-desk/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskBookingsRoute =
  AuthenticatedFrontDeskBookingsRouteImport.update({
    id: '/front-desk/bookings',
    path: '/front-desk/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoodPendingBillsRoute =
  AuthenticatedFoodPendingBillsRouteImport.update({
    id: '/food/pending-bills',
    path: '/food/pending-bills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoodNewRoute = AuthenticatedFoodNewRouteImport.update({
  id: '/food/new',
  path: '/food/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodKotsRoute = AuthenticatedFoodKotsRouteImport.update({
  id: '/food/kots',
  path: '/food/kots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodDashboardRoute =
  AuthenticatedFoodDashboardRouteImport.update({
    id: '/food/dashboard',
    path: '/food/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbackNewRoute =
  AuthenticatedFeedbackNewRouteImport.update({
    id: '/feedback/new',
    path: '/feedback/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesNewRoute =
  AuthenticatedExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommsNewRoute = AuthenticatedCommsNewRouteImport.update({
  id: '/comms/new',
  path: '/comms/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingMisRoute = AuthenticatedBillingMisRouteImport.update({
  id: '/billing/mis',
  path: '/billing/mis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingInvoicesRoute =
  AuthenticatedBillingInvoicesRouteImport.update({
    id: '/billing/invoices',
    path: '/billing/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBanquetNewRoute = AuthenticatedBanquetNewRouteImport.update({
  id: '/banquet/new',
  path: '/banquet/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBanquetBookingsRoute =
  AuthenticatedBanquetBookingsRouteImport.update({
    id: '/banquet/bookings',
    path: '/banquet/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrontDeskBookingIdRoute =
  AuthenticatedFrontDeskBookingIdRouteImport.update({
    id: '/front-desk/booking/$id',
    path: '/front-desk/booking/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFoodKotIdRoute = AuthenticatedFoodKotIdRouteImport.update({
  id: '/food/kot/$id',
  path: '/food/kot/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingFolioBookingIdRoute =
  AuthenticatedBillingFolioBookingIdRouteImport.update({
    id: '/billing/folio/$bookingId',
    path: '/billing/folio/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBanquetEventIdRoute =
  AuthenticatedBanquetEventIdRouteImport.update({
    id: '/banquet/event/$id',
    path: '/banquet/event/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBanquetBillIdRoute =
  AuthenticatedBanquetBillIdRouteImport.update({
    id: '/banquet/bill/$id',
    path: '/banquet/bill/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBanquetEventRoute =
  AuthenticatedBanquetEventRouteImport.update({
    id: '/banquet/event/',
    path: '/banquet/event/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/banquet/bookings': typeof AuthenticatedBanquetBookingsRoute
  '/banquet/new': typeof AuthenticatedBanquetNewRoute
  '/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/billing/mis': typeof AuthenticatedBillingMisRoute
  '/comms/new': typeof AuthenticatedCommsNewRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/food/dashboard': typeof AuthenticatedFoodDashboardRoute
  '/food/kots': typeof AuthenticatedFoodKotsRoute
  '/food/new': typeof AuthenticatedFoodNewRoute
  '/food/pending-bills': typeof AuthenticatedFoodPendingBillsRoute
  '/front-desk/bookings': typeof AuthenticatedFrontDeskBookingsRoute
  '/front-desk/calendar': typeof AuthenticatedFrontDeskCalendarRoute
  '/front-desk/in-house': typeof AuthenticatedFrontDeskInHouseRoute
  '/front-desk/new': typeof AuthenticatedFrontDeskNewRoute
  '/front-desk/rate-calendar': typeof AuthenticatedFrontDeskRateCalendarRoute
  '/guests/$id': typeof AuthenticatedGuestsIdRoute
  '/guests/new': typeof AuthenticatedGuestsNewRoute
  '/housekeeping/board': typeof AuthenticatedHousekeepingBoardRoute
  '/housekeeping/new': typeof AuthenticatedHousekeepingNewRoute
  '/housekeeping/tasks': typeof AuthenticatedHousekeepingTasksRoute
  '/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/vendors': typeof AuthenticatedInventoryVendorsRoute
  '/masters/channels': typeof AuthenticatedMastersChannelsRoute
  '/masters/expense-categories': typeof AuthenticatedMastersExpenseCategoriesRoute
  '/masters/halls': typeof AuthenticatedMastersHallsRoute
  '/masters/menu': typeof AuthenticatedMastersMenuRoute
  '/masters/message-templates': typeof AuthenticatedMastersMessageTemplatesRoute
  '/masters/printers': typeof AuthenticatedMastersPrintersRoute
  '/masters/rate-seasons': typeof AuthenticatedMastersRateSeasonsRoute
  '/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/masters/sundry-items': typeof AuthenticatedMastersSundryItemsRoute
  '/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/reports/activity': typeof AuthenticatedReportsActivityRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/reports/banquet': typeof AuthenticatedReportsBanquetRoute
  '/reports/bill-wise': typeof AuthenticatedReportsBillWiseRoute
  '/reports/cash-collection': typeof AuthenticatedReportsCashCollectionRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/date-wise-revenue': typeof AuthenticatedReportsDateWiseRevenueRoute
  '/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/reports/food-kot': typeof AuthenticatedReportsFoodKotRoute
  '/reports/gst': typeof AuthenticatedReportsGstRoute
  '/reports/guest-wise': typeof AuthenticatedReportsGuestWiseRoute
  '/reports/mis': typeof AuthenticatedReportsMisRoute
  '/reports/night-audit': typeof AuthenticatedReportsNightAuditRoute
  '/reports/room-wise': typeof AuthenticatedReportsRoomWiseRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/rooms/$roomNumber': typeof AuthenticatedRoomsRoomNumberRoute
  '/settings/hotel': typeof AuthenticatedSettingsHotelRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/staff/attendance': typeof AuthenticatedStaffAttendanceRoute
  '/staff/attendance-history': typeof AuthenticatedStaffAttendanceHistoryRoute
  '/staff/payroll': typeof AuthenticatedStaffPayrollRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/comms/': typeof AuthenticatedCommsIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/guests/': typeof AuthenticatedGuestsIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/masters/': typeof AuthenticatedMastersIndexRoute
  '/pos/': typeof AuthenticatedPosIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/restaurant/': typeof AuthenticatedRestaurantIndexRoute
  '/security/': typeof AuthenticatedSecurityIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
  '/banquet/event/': typeof AuthenticatedBanquetEventRoute
  '/banquet/bill/$id': typeof AuthenticatedBanquetBillIdRoute
  '/banquet/event/$id': typeof AuthenticatedBanquetEventIdRoute
  '/billing/folio/$bookingId': typeof AuthenticatedBillingFolioBookingIdRoute
  '/food/kot/$id': typeof AuthenticatedFoodKotIdRoute
  '/front-desk/booking/$id': typeof AuthenticatedFrontDeskBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/banquet/bookings': typeof AuthenticatedBanquetBookingsRoute
  '/banquet/new': typeof AuthenticatedBanquetNewRoute
  '/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/billing/mis': typeof AuthenticatedBillingMisRoute
  '/comms/new': typeof AuthenticatedCommsNewRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/food/dashboard': typeof AuthenticatedFoodDashboardRoute
  '/food/kots': typeof AuthenticatedFoodKotsRoute
  '/food/new': typeof AuthenticatedFoodNewRoute
  '/food/pending-bills': typeof AuthenticatedFoodPendingBillsRoute
  '/front-desk/bookings': typeof AuthenticatedFrontDeskBookingsRoute
  '/front-desk/calendar': typeof AuthenticatedFrontDeskCalendarRoute
  '/front-desk/in-house': typeof AuthenticatedFrontDeskInHouseRoute
  '/front-desk/new': typeof AuthenticatedFrontDeskNewRoute
  '/front-desk/rate-calendar': typeof AuthenticatedFrontDeskRateCalendarRoute
  '/guests/$id': typeof AuthenticatedGuestsIdRoute
  '/guests/new': typeof AuthenticatedGuestsNewRoute
  '/housekeeping/board': typeof AuthenticatedHousekeepingBoardRoute
  '/housekeeping/new': typeof AuthenticatedHousekeepingNewRoute
  '/housekeeping/tasks': typeof AuthenticatedHousekeepingTasksRoute
  '/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/vendors': typeof AuthenticatedInventoryVendorsRoute
  '/masters/channels': typeof AuthenticatedMastersChannelsRoute
  '/masters/expense-categories': typeof AuthenticatedMastersExpenseCategoriesRoute
  '/masters/halls': typeof AuthenticatedMastersHallsRoute
  '/masters/menu': typeof AuthenticatedMastersMenuRoute
  '/masters/message-templates': typeof AuthenticatedMastersMessageTemplatesRoute
  '/masters/printers': typeof AuthenticatedMastersPrintersRoute
  '/masters/rate-seasons': typeof AuthenticatedMastersRateSeasonsRoute
  '/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/masters/sundry-items': typeof AuthenticatedMastersSundryItemsRoute
  '/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/reports/activity': typeof AuthenticatedReportsActivityRoute
  '/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/reports/banquet': typeof AuthenticatedReportsBanquetRoute
  '/reports/bill-wise': typeof AuthenticatedReportsBillWiseRoute
  '/reports/cash-collection': typeof AuthenticatedReportsCashCollectionRoute
  '/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/reports/date-wise-revenue': typeof AuthenticatedReportsDateWiseRevenueRoute
  '/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/reports/food-kot': typeof AuthenticatedReportsFoodKotRoute
  '/reports/gst': typeof AuthenticatedReportsGstRoute
  '/reports/guest-wise': typeof AuthenticatedReportsGuestWiseRoute
  '/reports/mis': typeof AuthenticatedReportsMisRoute
  '/reports/night-audit': typeof AuthenticatedReportsNightAuditRoute
  '/reports/room-wise': typeof AuthenticatedReportsRoomWiseRoute
  '/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/rooms/$roomNumber': typeof AuthenticatedRoomsRoomNumberRoute
  '/settings/hotel': typeof AuthenticatedSettingsHotelRoute
  '/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/staff/attendance': typeof AuthenticatedStaffAttendanceRoute
  '/staff/attendance-history': typeof AuthenticatedStaffAttendanceHistoryRoute
  '/staff/payroll': typeof AuthenticatedStaffPayrollRoute
  '/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/comms': typeof AuthenticatedCommsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/feedback': typeof AuthenticatedFeedbackIndexRoute
  '/guests': typeof AuthenticatedGuestsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/masters': typeof AuthenticatedMastersIndexRoute
  '/pos': typeof AuthenticatedPosIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/restaurant': typeof AuthenticatedRestaurantIndexRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/whatsapp': typeof AuthenticatedWhatsappIndexRoute
  '/banquet/event': typeof AuthenticatedBanquetEventRoute
  '/banquet/bill/$id': typeof AuthenticatedBanquetBillIdRoute
  '/banquet/event/$id': typeof AuthenticatedBanquetEventIdRoute
  '/billing/folio/$bookingId': typeof AuthenticatedBillingFolioBookingIdRoute
  '/food/kot/$id': typeof AuthenticatedFoodKotIdRoute
  '/front-desk/booking/$id': typeof AuthenticatedFrontDeskBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/banquet/bookings': typeof AuthenticatedBanquetBookingsRoute
  '/_authenticated/banquet/new': typeof AuthenticatedBanquetNewRoute
  '/_authenticated/billing/invoices': typeof AuthenticatedBillingInvoicesRoute
  '/_authenticated/billing/mis': typeof AuthenticatedBillingMisRoute
  '/_authenticated/comms/new': typeof AuthenticatedCommsNewRoute
  '/_authenticated/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/_authenticated/feedback/new': typeof AuthenticatedFeedbackNewRoute
  '/_authenticated/food/dashboard': typeof AuthenticatedFoodDashboardRoute
  '/_authenticated/food/kots': typeof AuthenticatedFoodKotsRoute
  '/_authenticated/food/new': typeof AuthenticatedFoodNewRoute
  '/_authenticated/food/pending-bills': typeof AuthenticatedFoodPendingBillsRoute
  '/_authenticated/front-desk/bookings': typeof AuthenticatedFrontDeskBookingsRoute
  '/_authenticated/front-desk/calendar': typeof AuthenticatedFrontDeskCalendarRoute
  '/_authenticated/front-desk/in-house': typeof AuthenticatedFrontDeskInHouseRoute
  '/_authenticated/front-desk/new': typeof AuthenticatedFrontDeskNewRoute
  '/_authenticated/front-desk/rate-calendar': typeof AuthenticatedFrontDeskRateCalendarRoute
  '/_authenticated/guests/$id': typeof AuthenticatedGuestsIdRoute
  '/_authenticated/guests/new': typeof AuthenticatedGuestsNewRoute
  '/_authenticated/housekeeping/board': typeof AuthenticatedHousekeepingBoardRoute
  '/_authenticated/housekeeping/new': typeof AuthenticatedHousekeepingNewRoute
  '/_authenticated/housekeeping/tasks': typeof AuthenticatedHousekeepingTasksRoute
  '/_authenticated/inventory/items': typeof AuthenticatedInventoryItemsRoute
  '/_authenticated/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/_authenticated/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/_authenticated/inventory/vendors': typeof AuthenticatedInventoryVendorsRoute
  '/_authenticated/masters/channels': typeof AuthenticatedMastersChannelsRoute
  '/_authenticated/masters/expense-categories': typeof AuthenticatedMastersExpenseCategoriesRoute
  '/_authenticated/masters/halls': typeof AuthenticatedMastersHallsRoute
  '/_authenticated/masters/menu': typeof AuthenticatedMastersMenuRoute
  '/_authenticated/masters/message-templates': typeof AuthenticatedMastersMessageTemplatesRoute
  '/_authenticated/masters/printers': typeof AuthenticatedMastersPrintersRoute
  '/_authenticated/masters/rate-seasons': typeof AuthenticatedMastersRateSeasonsRoute
  '/_authenticated/masters/rooms': typeof AuthenticatedMastersRoomsRoute
  '/_authenticated/masters/staff': typeof AuthenticatedMastersStaffRoute
  '/_authenticated/masters/sundry-items': typeof AuthenticatedMastersSundryItemsRoute
  '/_authenticated/masters/tariff': typeof AuthenticatedMastersTariffRoute
  '/_authenticated/reports/activity': typeof AuthenticatedReportsActivityRoute
  '/_authenticated/reports/analytics': typeof AuthenticatedReportsAnalyticsRoute
  '/_authenticated/reports/banquet': typeof AuthenticatedReportsBanquetRoute
  '/_authenticated/reports/bill-wise': typeof AuthenticatedReportsBillWiseRoute
  '/_authenticated/reports/cash-collection': typeof AuthenticatedReportsCashCollectionRoute
  '/_authenticated/reports/daily': typeof AuthenticatedReportsDailyRoute
  '/_authenticated/reports/date-wise-revenue': typeof AuthenticatedReportsDateWiseRevenueRoute
  '/_authenticated/reports/expenses': typeof AuthenticatedReportsExpensesRoute
  '/_authenticated/reports/food-kot': typeof AuthenticatedReportsFoodKotRoute
  '/_authenticated/reports/gst': typeof AuthenticatedReportsGstRoute
  '/_authenticated/reports/guest-wise': typeof AuthenticatedReportsGuestWiseRoute
  '/_authenticated/reports/mis': typeof AuthenticatedReportsMisRoute
  '/_authenticated/reports/night-audit': typeof AuthenticatedReportsNightAuditRoute
  '/_authenticated/reports/room-wise': typeof AuthenticatedReportsRoomWiseRoute
  '/_authenticated/reports/sales': typeof AuthenticatedReportsSalesRoute
  '/_authenticated/rooms/$roomNumber': typeof AuthenticatedRoomsRoomNumberRoute
  '/_authenticated/settings/hotel': typeof AuthenticatedSettingsHotelRoute
  '/_authenticated/settings/whatsapp': typeof AuthenticatedSettingsWhatsappRoute
  '/_authenticated/staff/attendance': typeof AuthenticatedStaffAttendanceRoute
  '/_authenticated/staff/attendance-history': typeof AuthenticatedStaffAttendanceHistoryRoute
  '/_authenticated/staff/payroll': typeof AuthenticatedStaffPayrollRoute
  '/_authenticated/superadmin/dashboard': typeof AuthenticatedSuperadminDashboardRoute
  '/_authenticated/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/_authenticated/comms/': typeof AuthenticatedCommsIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/feedback/': typeof AuthenticatedFeedbackIndexRoute
  '/_authenticated/guests/': typeof AuthenticatedGuestsIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/masters/': typeof AuthenticatedMastersIndexRoute
  '/_authenticated/pos/': typeof AuthenticatedPosIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/restaurant/': typeof AuthenticatedRestaurantIndexRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
  '/_authenticated/banquet/event/': typeof AuthenticatedBanquetEventRoute
  '/_authenticated/banquet/bill/$id': typeof AuthenticatedBanquetBillIdRoute
  '/_authenticated/banquet/event/$id': typeof AuthenticatedBanquetEventIdRoute
  '/_authenticated/billing/folio/$bookingId': typeof AuthenticatedBillingFolioBookingIdRoute
  '/_authenticated/food/kot/$id': typeof AuthenticatedFoodKotIdRoute
  '/_authenticated/front-desk/booking/$id': typeof AuthenticatedFrontDeskBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/properties'
    | '/banquet/bookings'
    | '/banquet/new'
    | '/billing/invoices'
    | '/billing/mis'
    | '/comms/new'
    | '/expenses/new'
    | '/feedback/new'
    | '/food/dashboard'
    | '/food/kots'
    | '/food/new'
    | '/food/pending-bills'
    | '/front-desk/bookings'
    | '/front-desk/calendar'
    | '/front-desk/in-house'
    | '/front-desk/new'
    | '/front-desk/rate-calendar'
    | '/guests/$id'
    | '/guests/new'
    | '/housekeeping/board'
    | '/housekeeping/new'
    | '/housekeeping/tasks'
    | '/inventory/items'
    | '/inventory/movements'
    | '/inventory/stock'
    | '/inventory/vendors'
    | '/masters/channels'
    | '/masters/expense-categories'
    | '/masters/halls'
    | '/masters/menu'
    | '/masters/message-templates'
    | '/masters/printers'
    | '/masters/rate-seasons'
    | '/masters/rooms'
    | '/masters/staff'
    | '/masters/sundry-items'
    | '/masters/tariff'
    | '/reports/activity'
    | '/reports/analytics'
    | '/reports/banquet'
    | '/reports/bill-wise'
    | '/reports/cash-collection'
    | '/reports/daily'
    | '/reports/date-wise-revenue'
    | '/reports/expenses'
    | '/reports/food-kot'
    | '/reports/gst'
    | '/reports/guest-wise'
    | '/reports/mis'
    | '/reports/night-audit'
    | '/reports/room-wise'
    | '/reports/sales'
    | '/rooms/$roomNumber'
    | '/settings/hotel'
    | '/settings/whatsapp'
    | '/staff/attendance'
    | '/staff/attendance-history'
    | '/staff/payroll'
    | '/superadmin/dashboard'
    | '/superadmin/users'
    | '/channels/'
    | '/comms/'
    | '/expenses/'
    | '/feedback/'
    | '/guests/'
    | '/inventory/'
    | '/masters/'
    | '/pos/'
    | '/reports/'
    | '/restaurant/'
    | '/security/'
    | '/settings/'
    | '/staff/'
    | '/whatsapp/'
    | '/banquet/event/'
    | '/banquet/bill/$id'
    | '/banquet/event/$id'
    | '/billing/folio/$bookingId'
    | '/food/kot/$id'
    | '/front-desk/booking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/dashboard'
    | '/properties'
    | '/banquet/bookings'
    | '/banquet/new'
    | '/billing/invoices'
    | '/billing/mis'
    | '/comms/new'
    | '/expenses/new'
    | '/feedback/new'
    | '/food/dashboard'
    | '/food/kots'
    | '/food/new'
    | '/food/pending-bills'
    | '/front-desk/bookings'
    | '/front-desk/calendar'
    | '/front-desk/in-house'
    | '/front-desk/new'
    | '/front-desk/rate-calendar'
    | '/guests/$id'
    | '/guests/new'
    | '/housekeeping/board'
    | '/housekeeping/new'
    | '/housekeeping/tasks'
    | '/inventory/items'
    | '/inventory/movements'
    | '/inventory/stock'
    | '/inventory/vendors'
    | '/masters/channels'
    | '/masters/expense-categories'
    | '/masters/halls'
    | '/masters/menu'
    | '/masters/message-templates'
    | '/masters/printers'
    | '/masters/rate-seasons'
    | '/masters/rooms'
    | '/masters/staff'
    | '/masters/sundry-items'
    | '/masters/tariff'
    | '/reports/activity'
    | '/reports/analytics'
    | '/reports/banquet'
    | '/reports/bill-wise'
    | '/reports/cash-collection'
    | '/reports/daily'
    | '/reports/date-wise-revenue'
    | '/reports/expenses'
    | '/reports/food-kot'
    | '/reports/gst'
    | '/reports/guest-wise'
    | '/reports/mis'
    | '/reports/night-audit'
    | '/reports/room-wise'
    | '/reports/sales'
    | '/rooms/$roomNumber'
    | '/settings/hotel'
    | '/settings/whatsapp'
    | '/staff/attendance'
    | '/staff/attendance-history'
    | '/staff/payroll'
    | '/superadmin/dashboard'
    | '/superadmin/users'
    | '/channels'
    | '/comms'
    | '/expenses'
    | '/feedback'
    | '/guests'
    | '/inventory'
    | '/masters'
    | '/pos'
    | '/reports'
    | '/restaurant'
    | '/security'
    | '/settings'
    | '/staff'
    | '/whatsapp'
    | '/banquet/event'
    | '/banquet/bill/$id'
    | '/banquet/event/$id'
    | '/billing/folio/$bookingId'
    | '/food/kot/$id'
    | '/front-desk/booking/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/properties'
    | '/_authenticated/banquet/bookings'
    | '/_authenticated/banquet/new'
    | '/_authenticated/billing/invoices'
    | '/_authenticated/billing/mis'
    | '/_authenticated/comms/new'
    | '/_authenticated/expenses/new'
    | '/_authenticated/feedback/new'
    | '/_authenticated/food/dashboard'
    | '/_authenticated/food/kots'
    | '/_authenticated/food/new'
    | '/_authenticated/food/pending-bills'
    | '/_authenticated/front-desk/bookings'
    | '/_authenticated/front-desk/calendar'
    | '/_authenticated/front-desk/in-house'
    | '/_authenticated/front-desk/new'
    | '/_authenticated/front-desk/rate-calendar'
    | '/_authenticated/guests/$id'
    | '/_authenticated/guests/new'
    | '/_authenticated/housekeeping/board'
    | '/_authenticated/housekeeping/new'
    | '/_authenticated/housekeeping/tasks'
    | '/_authenticated/inventory/items'
    | '/_authenticated/inventory/movements'
    | '/_authenticated/inventory/stock'
    | '/_authenticated/inventory/vendors'
    | '/_authenticated/masters/channels'
    | '/_authenticated/masters/expense-categories'
    | '/_authenticated/masters/halls'
    | '/_authenticated/masters/menu'
    | '/_authenticated/masters/message-templates'
    | '/_authenticated/masters/printers'
    | '/_authenticated/masters/rate-seasons'
    | '/_authenticated/masters/rooms'
    | '/_authenticated/masters/staff'
    | '/_authenticated/masters/sundry-items'
    | '/_authenticated/masters/tariff'
    | '/_authenticated/reports/activity'
    | '/_authenticated/reports/analytics'
    | '/_authenticated/reports/banquet'
    | '/_authenticated/reports/bill-wise'
    | '/_authenticated/reports/cash-collection'
    | '/_authenticated/reports/daily'
    | '/_authenticated/reports/date-wise-revenue'
    | '/_authenticated/reports/expenses'
    | '/_authenticated/reports/food-kot'
    | '/_authenticated/reports/gst'
    | '/_authenticated/reports/guest-wise'
    | '/_authenticated/reports/mis'
    | '/_authenticated/reports/night-audit'
    | '/_authenticated/reports/room-wise'
    | '/_authenticated/reports/sales'
    | '/_authenticated/rooms/$roomNumber'
    | '/_authenticated/settings/hotel'
    | '/_authenticated/settings/whatsapp'
    | '/_authenticated/staff/attendance'
    | '/_authenticated/staff/attendance-history'
    | '/_authenticated/staff/payroll'
    | '/_authenticated/superadmin/dashboard'
    | '/_authenticated/superadmin/users'
    | '/_authenticated/channels/'
    | '/_authenticated/comms/'
    | '/_authenticated/expenses/'
    | '/_authenticated/feedback/'
    | '/_authenticated/guests/'
    | '/_authenticated/inventory/'
    | '/_authenticated/masters/'
    | '/_authenticated/pos/'
    | '/_authenticated/reports/'
    | '/_authenticated/restaurant/'
    | '/_authenticated/security/'
    | '/_authenticated/settings/'
    | '/_authenticated/staff/'
    | '/_authenticated/whatsapp/'
    | '/_authenticated/banquet/event/'
    | '/_authenticated/banquet/bill/$id'
    | '/_authenticated/banquet/event/$id'
    | '/_authenticated/billing/folio/$bookingId'
    | '/_authenticated/food/kot/$id'
    | '/_authenticated/front-desk/booking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/': {
      id: '/_authenticated/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof AuthenticatedWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/restaurant/': {
      id: '/_authenticated/restaurant/'
      path: '/restaurant'
      fullPath: '/restaurant/'
      preLoaderRoute: typeof AuthenticatedRestaurantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos/': {
      id: '/_authenticated/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof AuthenticatedPosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/': {
      id: '/_authenticated/masters/'
      path: '/masters'
      fullPath: '/masters/'
      preLoaderRoute: typeof AuthenticatedMastersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests/': {
      id: '/_authenticated/guests/'
      path: '/guests'
      fullPath: '/guests/'
      preLoaderRoute: typeof AuthenticatedGuestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/': {
      id: '/_authenticated/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof AuthenticatedFeedbackIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comms/': {
      id: '/_authenticated/comms/'
      path: '/comms'
      fullPath: '/comms/'
      preLoaderRoute: typeof AuthenticatedCommsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/users': {
      id: '/_authenticated/superadmin/users'
      path: '/superadmin/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof AuthenticatedSuperadminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/dashboard': {
      id: '/_authenticated/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof AuthenticatedSuperadminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/payroll': {
      id: '/_authenticated/staff/payroll'
      path: '/staff/payroll'
      fullPath: '/staff/payroll'
      preLoaderRoute: typeof AuthenticatedStaffPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/attendance-history': {
      id: '/_authenticated/staff/attendance-history'
      path: '/staff/attendance-history'
      fullPath: '/staff/attendance-history'
      preLoaderRoute: typeof AuthenticatedStaffAttendanceHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/attendance': {
      id: '/_authenticated/staff/attendance'
      path: '/staff/attendance'
      fullPath: '/staff/attendance'
      preLoaderRoute: typeof AuthenticatedStaffAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/whatsapp': {
      id: '/_authenticated/settings/whatsapp'
      path: '/settings/whatsapp'
      fullPath: '/settings/whatsapp'
      preLoaderRoute: typeof AuthenticatedSettingsWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/hotel': {
      id: '/_authenticated/settings/hotel'
      path: '/settings/hotel'
      fullPath: '/settings/hotel'
      preLoaderRoute: typeof AuthenticatedSettingsHotelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms/$roomNumber': {
      id: '/_authenticated/rooms/$roomNumber'
      path: '/rooms/$roomNumber'
      fullPath: '/rooms/$roomNumber'
      preLoaderRoute: typeof AuthenticatedRoomsRoomNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/sales': {
      id: '/_authenticated/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AuthenticatedReportsSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/room-wise': {
      id: '/_authenticated/reports/room-wise'
      path: '/reports/room-wise'
      fullPath: '/reports/room-wise'
      preLoaderRoute: typeof AuthenticatedReportsRoomWiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/night-audit': {
      id: '/_authenticated/reports/night-audit'
      path: '/reports/night-audit'
      fullPath: '/reports/night-audit'
      preLoaderRoute: typeof AuthenticatedReportsNightAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/mis': {
      id: '/_authenticated/reports/mis'
      path: '/reports/mis'
      fullPath: '/reports/mis'
      preLoaderRoute: typeof AuthenticatedReportsMisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/guest-wise': {
      id: '/_authenticated/reports/guest-wise'
      path: '/reports/guest-wise'
      fullPath: '/reports/guest-wise'
      preLoaderRoute: typeof AuthenticatedReportsGuestWiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/gst': {
      id: '/_authenticated/reports/gst'
      path: '/reports/gst'
      fullPath: '/reports/gst'
      preLoaderRoute: typeof AuthenticatedReportsGstRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/food-kot': {
      id: '/_authenticated/reports/food-kot'
      path: '/reports/food-kot'
      fullPath: '/reports/food-kot'
      preLoaderRoute: typeof AuthenticatedReportsFoodKotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/expenses': {
      id: '/_authenticated/reports/expenses'
      path: '/reports/expenses'
      fullPath: '/reports/expenses'
      preLoaderRoute: typeof AuthenticatedReportsExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/date-wise-revenue': {
      id: '/_authenticated/reports/date-wise-revenue'
      path: '/reports/date-wise-revenue'
      fullPath: '/reports/date-wise-revenue'
      preLoaderRoute: typeof AuthenticatedReportsDateWiseRevenueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/daily': {
      id: '/_authenticated/reports/daily'
      path: '/reports/daily'
      fullPath: '/reports/daily'
      preLoaderRoute: typeof AuthenticatedReportsDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/cash-collection': {
      id: '/_authenticated/reports/cash-collection'
      path: '/reports/cash-collection'
      fullPath: '/reports/cash-collection'
      preLoaderRoute: typeof AuthenticatedReportsCashCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/bill-wise': {
      id: '/_authenticated/reports/bill-wise'
      path: '/reports/bill-wise'
      fullPath: '/reports/bill-wise'
      preLoaderRoute: typeof AuthenticatedReportsBillWiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/banquet': {
      id: '/_authenticated/reports/banquet'
      path: '/reports/banquet'
      fullPath: '/reports/banquet'
      preLoaderRoute: typeof AuthenticatedReportsBanquetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/analytics': {
      id: '/_authenticated/reports/analytics'
      path: '/reports/analytics'
      fullPath: '/reports/analytics'
      preLoaderRoute: typeof AuthenticatedReportsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/activity': {
      id: '/_authenticated/reports/activity'
      path: '/reports/activity'
      fullPath: '/reports/activity'
      preLoaderRoute: typeof AuthenticatedReportsActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/tariff': {
      id: '/_authenticated/masters/tariff'
      path: '/masters/tariff'
      fullPath: '/masters/tariff'
      preLoaderRoute: typeof AuthenticatedMastersTariffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/sundry-items': {
      id: '/_authenticated/masters/sundry-items'
      path: '/masters/sundry-items'
      fullPath: '/masters/sundry-items'
      preLoaderRoute: typeof AuthenticatedMastersSundryItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/staff': {
      id: '/_authenticated/masters/staff'
      path: '/masters/staff'
      fullPath: '/masters/staff'
      preLoaderRoute: typeof AuthenticatedMastersStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/rooms': {
      id: '/_authenticated/masters/rooms'
      path: '/masters/rooms'
      fullPath: '/masters/rooms'
      preLoaderRoute: typeof AuthenticatedMastersRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/rate-seasons': {
      id: '/_authenticated/masters/rate-seasons'
      path: '/masters/rate-seasons'
      fullPath: '/masters/rate-seasons'
      preLoaderRoute: typeof AuthenticatedMastersRateSeasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/printers': {
      id: '/_authenticated/masters/printers'
      path: '/masters/printers'
      fullPath: '/masters/printers'
      preLoaderRoute: typeof AuthenticatedMastersPrintersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/message-templates': {
      id: '/_authenticated/masters/message-templates'
      path: '/masters/message-templates'
      fullPath: '/masters/message-templates'
      preLoaderRoute: typeof AuthenticatedMastersMessageTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/menu': {
      id: '/_authenticated/masters/menu'
      path: '/masters/menu'
      fullPath: '/masters/menu'
      preLoaderRoute: typeof AuthenticatedMastersMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/halls': {
      id: '/_authenticated/masters/halls'
      path: '/masters/halls'
      fullPath: '/masters/halls'
      preLoaderRoute: typeof AuthenticatedMastersHallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/expense-categories': {
      id: '/_authenticated/masters/expense-categories'
      path: '/masters/expense-categories'
      fullPath: '/masters/expense-categories'
      preLoaderRoute: typeof AuthenticatedMastersExpenseCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/masters/channels': {
      id: '/_authenticated/masters/channels'
      path: '/masters/channels'
      fullPath: '/masters/channels'
      preLoaderRoute: typeof AuthenticatedMastersChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/vendors': {
      id: '/_authenticated/inventory/vendors'
      path: '/inventory/vendors'
      fullPath: '/inventory/vendors'
      preLoaderRoute: typeof AuthenticatedInventoryVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/stock': {
      id: '/_authenticated/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AuthenticatedInventoryStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/movements': {
      id: '/_authenticated/inventory/movements'
      path: '/inventory/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AuthenticatedInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/items': {
      id: '/_authenticated/inventory/items'
      path: '/inventory/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof AuthenticatedInventoryItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/housekeeping/tasks': {
      id: '/_authenticated/housekeeping/tasks'
      path: '/housekeeping/tasks'
      fullPath: '/housekeeping/tasks'
      preLoaderRoute: typeof AuthenticatedHousekeepingTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/housekeeping/new': {
      id: '/_authenticated/housekeeping/new'
      path: '/housekeeping/new'
      fullPath: '/housekeeping/new'
      preLoaderRoute: typeof AuthenticatedHousekeepingNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/housekeeping/board': {
      id: '/_authenticated/housekeeping/board'
      path: '/housekeeping/board'
      fullPath: '/housekeeping/board'
      preLoaderRoute: typeof AuthenticatedHousekeepingBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests/new': {
      id: '/_authenticated/guests/new'
      path: '/guests/new'
      fullPath: '/guests/new'
      preLoaderRoute: typeof AuthenticatedGuestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guests/$id': {
      id: '/_authenticated/guests/$id'
      path: '/guests/$id'
      fullPath: '/guests/$id'
      preLoaderRoute: typeof AuthenticatedGuestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/rate-calendar': {
      id: '/_authenticated/front-desk/rate-calendar'
      path: '/front-desk/rate-calendar'
      fullPath: '/front-desk/rate-calendar'
      preLoaderRoute: typeof AuthenticatedFrontDeskRateCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/new': {
      id: '/_authenticated/front-desk/new'
      path: '/front-desk/new'
      fullPath: '/front-desk/new'
      preLoaderRoute: typeof AuthenticatedFrontDeskNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/in-house': {
      id: '/_authenticated/front-desk/in-house'
      path: '/front-desk/in-house'
      fullPath: '/front-desk/in-house'
      preLoaderRoute: typeof AuthenticatedFrontDeskInHouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/calendar': {
      id: '/_authenticated/front-desk/calendar'
      path: '/front-desk/calendar'
      fullPath: '/front-desk/calendar'
      preLoaderRoute: typeof AuthenticatedFrontDeskCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/bookings': {
      id: '/_authenticated/front-desk/bookings'
      path: '/front-desk/bookings'
      fullPath: '/front-desk/bookings'
      preLoaderRoute: typeof AuthenticatedFrontDeskBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/pending-bills': {
      id: '/_authenticated/food/pending-bills'
      path: '/food/pending-bills'
      fullPath: '/food/pending-bills'
      preLoaderRoute: typeof AuthenticatedFoodPendingBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/new': {
      id: '/_authenticated/food/new'
      path: '/food/new'
      fullPath: '/food/new'
      preLoaderRoute: typeof AuthenticatedFoodNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/kots': {
      id: '/_authenticated/food/kots'
      path: '/food/kots'
      fullPath: '/food/kots'
      preLoaderRoute: typeof AuthenticatedFoodKotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/dashboard': {
      id: '/_authenticated/food/dashboard'
      path: '/food/dashboard'
      fullPath: '/food/dashboard'
      preLoaderRoute: typeof AuthenticatedFoodDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedback/new': {
      id: '/_authenticated/feedback/new'
      path: '/feedback/new'
      fullPath: '/feedback/new'
      preLoaderRoute: typeof AuthenticatedFeedbackNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/new': {
      id: '/_authenticated/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthenticatedExpensesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comms/new': {
      id: '/_authenticated/comms/new'
      path: '/comms/new'
      fullPath: '/comms/new'
      preLoaderRoute: typeof AuthenticatedCommsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/mis': {
      id: '/_authenticated/billing/mis'
      path: '/billing/mis'
      fullPath: '/billing/mis'
      preLoaderRoute: typeof AuthenticatedBillingMisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/invoices': {
      id: '/_authenticated/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/billing/invoices'
      preLoaderRoute: typeof AuthenticatedBillingInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/new': {
      id: '/_authenticated/banquet/new'
      path: '/banquet/new'
      fullPath: '/banquet/new'
      preLoaderRoute: typeof AuthenticatedBanquetNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/bookings': {
      id: '/_authenticated/banquet/bookings'
      path: '/banquet/bookings'
      fullPath: '/banquet/bookings'
      preLoaderRoute: typeof AuthenticatedBanquetBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/front-desk/booking/$id': {
      id: '/_authenticated/front-desk/booking/$id'
      path: '/front-desk/booking/$id'
      fullPath: '/front-desk/booking/$id'
      preLoaderRoute: typeof AuthenticatedFrontDeskBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food/kot/$id': {
      id: '/_authenticated/food/kot/$id'
      path: '/food/kot/$id'
      fullPath: '/food/kot/$id'
      preLoaderRoute: typeof AuthenticatedFoodKotIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/folio/$bookingId': {
      id: '/_authenticated/billing/folio/$bookingId'
      path: '/billing/folio/$bookingId'
      fullPath: '/billing/folio/$bookingId'
      preLoaderRoute: typeof AuthenticatedBillingFolioBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/event/$id': {
      id: '/_authenticated/banquet/event/$id'
      path: '/banquet/event/$id'
      fullPath: '/banquet/event/$id'
      preLoaderRoute: typeof AuthenticatedBanquetEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/bill/$id': {
      id: '/_authenticated/banquet/bill/$id'
      path: '/banquet/bill/$id'
      fullPath: '/banquet/bill/$id'
      preLoaderRoute: typeof AuthenticatedBanquetBillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banquet/event/': {
      id: '/_authenticated/banquet/event/'
      path: '/banquet/event'
      fullPath: '/banquet/event/'
      preLoaderRoute: typeof AuthenticatedBanquetEventRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedBanquetBookingsRoute: typeof AuthenticatedBanquetBookingsRoute
  AuthenticatedBanquetNewRoute: typeof AuthenticatedBanquetNewRoute
  AuthenticatedBillingInvoicesRoute: typeof AuthenticatedBillingInvoicesRoute
  AuthenticatedBillingMisRoute: typeof AuthenticatedBillingMisRoute
  AuthenticatedCommsNewRoute: typeof AuthenticatedCommsNewRoute
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute
  AuthenticatedFeedbackNewRoute: typeof AuthenticatedFeedbackNewRoute
  AuthenticatedFoodDashboardRoute: typeof AuthenticatedFoodDashboardRoute
  AuthenticatedFoodKotsRoute: typeof AuthenticatedFoodKotsRoute
  AuthenticatedFoodNewRoute: typeof AuthenticatedFoodNewRoute
  AuthenticatedFoodPendingBillsRoute: typeof AuthenticatedFoodPendingBillsRoute
  AuthenticatedFrontDeskBookingsRoute: typeof AuthenticatedFrontDeskBookingsRoute
  AuthenticatedFrontDeskCalendarRoute: typeof AuthenticatedFrontDeskCalendarRoute
  AuthenticatedFrontDeskInHouseRoute: typeof AuthenticatedFrontDeskInHouseRoute
  AuthenticatedFrontDeskNewRoute: typeof AuthenticatedFrontDeskNewRoute
  AuthenticatedFrontDeskRateCalendarRoute: typeof AuthenticatedFrontDeskRateCalendarRoute
  AuthenticatedGuestsIdRoute: typeof AuthenticatedGuestsIdRoute
  AuthenticatedGuestsNewRoute: typeof AuthenticatedGuestsNewRoute
  AuthenticatedHousekeepingBoardRoute: typeof AuthenticatedHousekeepingBoardRoute
  AuthenticatedHousekeepingNewRoute: typeof AuthenticatedHousekeepingNewRoute
  AuthenticatedHousekeepingTasksRoute: typeof AuthenticatedHousekeepingTasksRoute
  AuthenticatedInventoryItemsRoute: typeof AuthenticatedInventoryItemsRoute
  AuthenticatedInventoryMovementsRoute: typeof AuthenticatedInventoryMovementsRoute
  AuthenticatedInventoryStockRoute: typeof AuthenticatedInventoryStockRoute
  AuthenticatedInventoryVendorsRoute: typeof AuthenticatedInventoryVendorsRoute
  AuthenticatedMastersChannelsRoute: typeof AuthenticatedMastersChannelsRoute
  AuthenticatedMastersExpenseCategoriesRoute: typeof AuthenticatedMastersExpenseCategoriesRoute
  AuthenticatedMastersHallsRoute: typeof AuthenticatedMastersHallsRoute
  AuthenticatedMastersMenuRoute: typeof AuthenticatedMastersMenuRoute
  AuthenticatedMastersMessageTemplatesRoute: typeof AuthenticatedMastersMessageTemplatesRoute
  AuthenticatedMastersPrintersRoute: typeof AuthenticatedMastersPrintersRoute
  AuthenticatedMastersRateSeasonsRoute: typeof AuthenticatedMastersRateSeasonsRoute
  AuthenticatedMastersRoomsRoute: typeof AuthenticatedMastersRoomsRoute
  AuthenticatedMastersStaffRoute: typeof AuthenticatedMastersStaffRoute
  AuthenticatedMastersSundryItemsRoute: typeof AuthenticatedMastersSundryItemsRoute
  AuthenticatedMastersTariffRoute: typeof AuthenticatedMastersTariffRoute
  AuthenticatedReportsActivityRoute: typeof AuthenticatedReportsActivityRoute
  AuthenticatedReportsAnalyticsRoute: typeof AuthenticatedReportsAnalyticsRoute
  AuthenticatedReportsBanquetRoute: typeof AuthenticatedReportsBanquetRoute
  AuthenticatedReportsBillWiseRoute: typeof AuthenticatedReportsBillWiseRoute
  AuthenticatedReportsCashCollectionRoute: typeof AuthenticatedReportsCashCollectionRoute
  AuthenticatedReportsDailyRoute: typeof AuthenticatedReportsDailyRoute
  AuthenticatedReportsDateWiseRevenueRoute: typeof AuthenticatedReportsDateWiseRevenueRoute
  AuthenticatedReportsExpensesRoute: typeof AuthenticatedReportsExpensesRoute
  AuthenticatedReportsFoodKotRoute: typeof AuthenticatedReportsFoodKotRoute
  AuthenticatedReportsGstRoute: typeof AuthenticatedReportsGstRoute
  AuthenticatedReportsGuestWiseRoute: typeof AuthenticatedReportsGuestWiseRoute
  AuthenticatedReportsMisRoute: typeof AuthenticatedReportsMisRoute
  AuthenticatedReportsNightAuditRoute: typeof AuthenticatedReportsNightAuditRoute
  AuthenticatedReportsRoomWiseRoute: typeof AuthenticatedReportsRoomWiseRoute
  AuthenticatedReportsSalesRoute: typeof AuthenticatedReportsSalesRoute
  AuthenticatedRoomsRoomNumberRoute: typeof AuthenticatedRoomsRoomNumberRoute
  AuthenticatedSettingsHotelRoute: typeof AuthenticatedSettingsHotelRoute
  AuthenticatedSettingsWhatsappRoute: typeof AuthenticatedSettingsWhatsappRoute
  AuthenticatedStaffAttendanceRoute: typeof AuthenticatedStaffAttendanceRoute
  AuthenticatedStaffAttendanceHistoryRoute: typeof AuthenticatedStaffAttendanceHistoryRoute
  AuthenticatedStaffPayrollRoute: typeof AuthenticatedStaffPayrollRoute
  AuthenticatedSuperadminDashboardRoute: typeof AuthenticatedSuperadminDashboardRoute
  AuthenticatedSuperadminUsersRoute: typeof AuthenticatedSuperadminUsersRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
  AuthenticatedCommsIndexRoute: typeof AuthenticatedCommsIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedFeedbackIndexRoute: typeof AuthenticatedFeedbackIndexRoute
  AuthenticatedGuestsIndexRoute: typeof AuthenticatedGuestsIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedMastersIndexRoute: typeof AuthenticatedMastersIndexRoute
  AuthenticatedPosIndexRoute: typeof AuthenticatedPosIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRestaurantIndexRoute: typeof AuthenticatedRestaurantIndexRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedWhatsappIndexRoute: typeof AuthenticatedWhatsappIndexRoute
  AuthenticatedBanquetEventRoute: typeof AuthenticatedBanquetEventRoute
  AuthenticatedBanquetBillIdRoute: typeof AuthenticatedBanquetBillIdRoute
  AuthenticatedBanquetEventIdRoute: typeof AuthenticatedBanquetEventIdRoute
  AuthenticatedBillingFolioBookingIdRoute: typeof AuthenticatedBillingFolioBookingIdRoute
  AuthenticatedFoodKotIdRoute: typeof AuthenticatedFoodKotIdRoute
  AuthenticatedFrontDeskBookingIdRoute: typeof AuthenticatedFrontDeskBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedBanquetBookingsRoute: AuthenticatedBanquetBookingsRoute,
  AuthenticatedBanquetNewRoute: AuthenticatedBanquetNewRoute,
  AuthenticatedBillingInvoicesRoute: AuthenticatedBillingInvoicesRoute,
  AuthenticatedBillingMisRoute: AuthenticatedBillingMisRoute,
  AuthenticatedCommsNewRoute: AuthenticatedCommsNewRoute,
  AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
  AuthenticatedFeedbackNewRoute: AuthenticatedFeedbackNewRoute,
  AuthenticatedFoodDashboardRoute: AuthenticatedFoodDashboardRoute,
  AuthenticatedFoodKotsRoute: AuthenticatedFoodKotsRoute,
  AuthenticatedFoodNewRoute: AuthenticatedFoodNewRoute,
  AuthenticatedFoodPendingBillsRoute: AuthenticatedFoodPendingBillsRoute,
  AuthenticatedFrontDeskBookingsRoute: AuthenticatedFrontDeskBookingsRoute,
  AuthenticatedFrontDeskCalendarRoute: AuthenticatedFrontDeskCalendarRoute,
  AuthenticatedFrontDeskInHouseRoute: AuthenticatedFrontDeskInHouseRoute,
  AuthenticatedFrontDeskNewRoute: AuthenticatedFrontDeskNewRoute,
  AuthenticatedFrontDeskRateCalendarRoute:
    AuthenticatedFrontDeskRateCalendarRoute,
  AuthenticatedGuestsIdRoute: AuthenticatedGuestsIdRoute,
  AuthenticatedGuestsNewRoute: AuthenticatedGuestsNewRoute,
  AuthenticatedHousekeepingBoardRoute: AuthenticatedHousekeepingBoardRoute,
  AuthenticatedHousekeepingNewRoute: AuthenticatedHousekeepingNewRoute,
  AuthenticatedHousekeepingTasksRoute: AuthenticatedHousekeepingTasksRoute,
  AuthenticatedInventoryItemsRoute: AuthenticatedInventoryItemsRoute,
  AuthenticatedInventoryMovementsRoute: AuthenticatedInventoryMovementsRoute,
  AuthenticatedInventoryStockRoute: AuthenticatedInventoryStockRoute,
  AuthenticatedInventoryVendorsRoute: AuthenticatedInventoryVendorsRoute,
  AuthenticatedMastersChannelsRoute: AuthenticatedMastersChannelsRoute,
  AuthenticatedMastersExpenseCategoriesRoute:
    AuthenticatedMastersExpenseCategoriesRoute,
  AuthenticatedMastersHallsRoute: AuthenticatedMastersHallsRoute,
  AuthenticatedMastersMenuRoute: AuthenticatedMastersMenuRoute,
  AuthenticatedMastersMessageTemplatesRoute:
    AuthenticatedMastersMessageTemplatesRoute,
  AuthenticatedMastersPrintersRoute: AuthenticatedMastersPrintersRoute,
  AuthenticatedMastersRateSeasonsRoute: AuthenticatedMastersRateSeasonsRoute,
  AuthenticatedMastersRoomsRoute: AuthenticatedMastersRoomsRoute,
  AuthenticatedMastersStaffRoute: AuthenticatedMastersStaffRoute,
  AuthenticatedMastersSundryItemsRoute: AuthenticatedMastersSundryItemsRoute,
  AuthenticatedMastersTariffRoute: AuthenticatedMastersTariffRoute,
  AuthenticatedReportsActivityRoute: AuthenticatedReportsActivityRoute,
  AuthenticatedReportsAnalyticsRoute: AuthenticatedReportsAnalyticsRoute,
  AuthenticatedReportsBanquetRoute: AuthenticatedReportsBanquetRoute,
  AuthenticatedReportsBillWiseRoute: AuthenticatedReportsBillWiseRoute,
  AuthenticatedReportsCashCollectionRoute:
    AuthenticatedReportsCashCollectionRoute,
  AuthenticatedReportsDailyRoute: AuthenticatedReportsDailyRoute,
  AuthenticatedReportsDateWiseRevenueRoute:
    AuthenticatedReportsDateWiseRevenueRoute,
  AuthenticatedReportsExpensesRoute: AuthenticatedReportsExpensesRoute,
  AuthenticatedReportsFoodKotRoute: AuthenticatedReportsFoodKotRoute,
  AuthenticatedReportsGstRoute: AuthenticatedReportsGstRoute,
  AuthenticatedReportsGuestWiseRoute: AuthenticatedReportsGuestWiseRoute,
  AuthenticatedReportsMisRoute: AuthenticatedReportsMisRoute,
  AuthenticatedReportsNightAuditRoute: AuthenticatedReportsNightAuditRoute,
  AuthenticatedReportsRoomWiseRoute: AuthenticatedReportsRoomWiseRoute,
  AuthenticatedReportsSalesRoute: AuthenticatedReportsSalesRoute,
  AuthenticatedRoomsRoomNumberRoute: AuthenticatedRoomsRoomNumberRoute,
  AuthenticatedSettingsHotelRoute: AuthenticatedSettingsHotelRoute,
  AuthenticatedSettingsWhatsappRoute: AuthenticatedSettingsWhatsappRoute,
  AuthenticatedStaffAttendanceRoute: AuthenticatedStaffAttendanceRoute,
  AuthenticatedStaffAttendanceHistoryRoute:
    AuthenticatedStaffAttendanceHistoryRoute,
  AuthenticatedStaffPayrollRoute: AuthenticatedStaffPayrollRoute,
  AuthenticatedSuperadminDashboardRoute: AuthenticatedSuperadminDashboardRoute,
  AuthenticatedSuperadminUsersRoute: AuthenticatedSuperadminUsersRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
  AuthenticatedCommsIndexRoute: AuthenticatedCommsIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedFeedbackIndexRoute: AuthenticatedFeedbackIndexRoute,
  AuthenticatedGuestsIndexRoute: AuthenticatedGuestsIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedMastersIndexRoute: AuthenticatedMastersIndexRoute,
  AuthenticatedPosIndexRoute: AuthenticatedPosIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRestaurantIndexRoute: AuthenticatedRestaurantIndexRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedWhatsappIndexRoute: AuthenticatedWhatsappIndexRoute,
  AuthenticatedBanquetEventRoute: AuthenticatedBanquetEventRoute,
  AuthenticatedBanquetBillIdRoute: AuthenticatedBanquetBillIdRoute,
  AuthenticatedBanquetEventIdRoute: AuthenticatedBanquetEventIdRoute,
  AuthenticatedBillingFolioBookingIdRoute:
    AuthenticatedBillingFolioBookingIdRoute,
  AuthenticatedFoodKotIdRoute: AuthenticatedFoodKotIdRoute,
  AuthenticatedFrontDeskBookingIdRoute: AuthenticatedFrontDeskBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
