ALTER POLICY "bookings_create" ON public."bookings" WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'create'::text)))));
ALTER POLICY "bookings_delete" ON public."bookings" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'delete'::text)))));
ALTER POLICY "bookings_edit" ON public."bookings" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text))))) WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text)))));
ALTER POLICY "bookings_view" ON public."bookings" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'view'::text)))));
ALTER POLICY "booking_rooms_create" ON public."booking_rooms" WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'create'::text)))));
ALTER POLICY "booking_rooms_delete" ON public."booking_rooms" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'delete'::text)))));
ALTER POLICY "booking_rooms_edit" ON public."booking_rooms" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text))))) WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text)))));
ALTER POLICY "booking_rooms_view" ON public."booking_rooms" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'view'::text)))));
ALTER POLICY "booking_guests_create" ON public."booking_guests" WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'create'::text)))));
ALTER POLICY "booking_guests_delete" ON public."booking_guests" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'delete'::text)))));
ALTER POLICY "booking_guests_edit" ON public."booking_guests" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text))))) WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text)))));
ALTER POLICY "booking_guests_view" ON public."booking_guests" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'view'::text)))));
ALTER POLICY "beb_create" ON public."booking_extra_beds" WITH CHECK ((((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'create'::text)))) OR ((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text))))));
ALTER POLICY "beb_delete" ON public."booking_extra_beds" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'delete'::text)))));
ALTER POLICY "beb_edit" ON public."booking_extra_beds" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text))))) WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'edit'::text)))));
ALTER POLICY "beb_view" ON public."booking_extra_beds" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'bookings'::text, 'view'::text)))));
ALTER POLICY "folios_create" ON public."folios" WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'create'::text)))));
ALTER POLICY "folios_delete" ON public."folios" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'delete'::text)))));
ALTER POLICY "folios_edit" ON public."folios" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'edit'::text))))) WITH CHECK (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'edit'::text)))));
ALTER POLICY "folios_view" ON public."folios" USING (((SELECT public.is_superadmin(auth.uid())) OR (property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'view'::text)))));
ALTER POLICY "folio_charges_create" ON public."folio_charges" WITH CHECK ((EXISTS ( SELECT 1
   FROM folios f
  WHERE ((f.id = folio_charges.folio_id) AND ((SELECT public.is_superadmin(auth.uid())) OR (f.property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (f.property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'create'::text))))))));
ALTER POLICY "folio_charges_delete" ON public."folio_charges" USING ((EXISTS ( SELECT 1
   FROM folios f
  WHERE ((f.id = folio_charges.folio_id) AND ((SELECT public.is_superadmin(auth.uid())) OR (f.property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (f.property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'delete'::text))))))));
ALTER POLICY "folio_charges_edit" ON public."folio_charges" USING ((EXISTS ( SELECT 1
   FROM folios f
  WHERE ((f.id = folio_charges.folio_id) AND ((SELECT public.is_superadmin(auth.uid())) OR (f.property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (f.property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'edit'::text)))))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM folios f
  WHERE ((f.id = folio_charges.folio_id) AND ((SELECT public.is_superadmin(auth.uid())) OR (f.property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (f.property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'edit'::text))))))));
ALTER POLICY "folio_charges_view" ON public."folio_charges" USING ((EXISTS ( SELECT 1
   FROM folios f
  WHERE ((f.id = folio_charges.folio_id) AND ((SELECT public.is_superadmin(auth.uid())) OR (f.property_id IS NOT NULL AND (SELECT public.is_global_owner(auth.uid()))) OR (f.property_id IN (SELECT public.permitted_property_ids(auth.uid(), 'invoices'::text, 'view'::text))))))));